version: '3.1'
services:
  shib-service-example:
    image: uscdev/shib-service-example
    ports:
      - 80:80
      - 443:443
    secrets:
      - apache.crt
      - apache.key
      - sp-key.pem
      - sp-cert.pem
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
secrets:
  apache.crt:
    external: true
  apache.key:
    external: true
  sp-key.pem:
    external: true
  sp-cert.pem:
    external: true
