version: '3.6'
services:
  shib-service-example:
    image: uscdev/shib-service-example
    ports:
      - 8986:80
      - 8987:443
    environment:
      - SERVER_NAME=${SERVER_NAME}
    networks:
      - proxy
    secrets:
      - apache.crt
      - apache.key
      - sp-key.pem
      - sp-cert.pem
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.httpsOnly=true
        - com.df.port=443
        - com.df.serviceDomain=shib-service-example.docker.usc.edu
        - com.df.sslVerifyNone=true
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
networks:
  proxy:
    external:
      name: proxy
secrets:
  apache.crt:
    external: true
  apache.key:
    external: true
  sp-key.pem:
    external: true
  sp-cert.pem:
    external: true
